name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test std-encoding on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@v2.0.0
      - name: install deno
        uses: denolib/setup-deno@v2.0.0
      - name: run tests
        run: deno test
